# Site Settings
title: Jekflix | A theme for Jekyll
email: imitaz88@gmail.com
description: This is my html blog centre
baseurl: "/jekflix/" # the subpath of your site, e.g. /blog
url: "https://www.test.athelo.net" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Aezo
user_description: Some text about you.
disqus_username: checkR

# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: axlelr
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
